apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi  # How much storage is allocated to the PVC
