# PVC for backup storage in case we need to revert to a previos version

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backups
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi  
