apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  selector: { app: minecraft } # Must be the same as the one in the deployment yaml
  ports:
    - { name: minecraft, port: 25565, targetPort: 25565 }
    - { name: rcon, port: 25575, targetPort: 25575 }
